### ISSUE TITLE
怎么进入系统

### ISSUE THREAD

**Issue by caijh0316** [e-yunduan/library#5]
部署好了，按照文档操作到了注册码这一步，可是访问域名后，只有文件列表，这个系统入口在哪里？管理界面又在哪里呢？

**Comment by forecho** [comment]
@caijh0316 本项目是基于 Yii2 高级模板开发，所以你可以通过查看[入门文档](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide-zh-CN/README.md)了解基本使用。
